### ISSUE TITLE
How to use it with postman

### ISSUE THREAD

**Issue by nghiatv** [christiannwamba/scotch-entrust#1]
Hi Chirstian.
This code is very useful to me. But im newbie in laravel.
Please teach me how to use it with Postman.
how to create a user with role? how to create a role?..
I will be very grateful for it. Sorry for my English but i hope you can understand and help me

**Comment by christiannwamba** [comment]
To create role:
https://drive.google.com/file/d/0B5H-1JjaRTTjeVNWNFlGV0ZuRHc/view?usp=sharing
To assign role to user:
https://drive.google.com/file/d/0B5H-1JjaRTTjNE1xSG1HZ1dILXM/view?usp=sharing

Those are images of how you can test the endpoints you requested using Postman.

Your English is good by the way :)
